_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    NAME: RotatedAnchorGenerator
    ANGLES: [[-90,-60,-30,0,30,60,90]]
    ASPECT_RATIOS: [[0.2, 0.5, 1.0]]
  PROPOSAL_GENERATOR:
    NAME: RRPN
  RPN:
    BBOX_REG_WEIGHTS: (1,1,1,1,1,)
  ROI_BOX_HEAD:
    POOLER_TYPE: ROIAlignRotated
    BBOX_REG_WEIGHTS: (10,10,5,5,5)
  ROI_HEADS:
    NAME: RROIHeads
    NUM_CLASSES: 1
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  CHECKPOINT_PERIOD: 2000
INPUT:
  MIN_SIZE_TRAIN: (688, 720, 752)
  MIN_SIZE_TEST: 720
DATASETS:
  TRAIN: ('icdar_2015_train',)
  TEST: ('icdar_2015_test',)
